wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.4
    framework: huggingface
    huggingface_version: 4.26.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1687181289.448454
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 71
      - 80
      - 83
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 71
      - 80
      - 83
      3:
      - 2
      - 23
      4: 3.10.8
      5: 0.15.4
      6: 4.26.0
      8:
      - 3
      - 5
